const MENU=MenuModel.items;
const STATUS=['Order placed','Preparing','Out for delivery','Delivered'];
const PAGE_SIZE=12;
const state={user:StoreModel.read('user'),cart:StoreModel.read('cart',[]),orders:StoreModel.read('orders',[]),category:'All',search:'',page:1,activeOrder:null};
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function money(n){return new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n)}
function orderDate(timestamp,long=false){return new Intl.DateTimeFormat('en-PH',{dateStyle:long?'long':'medium',timeStyle:'short',timeZone:'Asia/Manila'}).format(new Date(timestamp))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(message){const el=$('.toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}
function renderCategories(){const cats=MenuModel.categories();$('.categories').innerHTML=cats.map(c=>`<button class="category-btn ${c===state.category?'active':''}" data-category="${c}" role="tab">${c}</button>`).join('')}
function dishCards(dishes){return dishes.map(x=>`<article class="dish-card reveal ${x.isAvailable?'':'dish-unavailable'}"><div class="dish-image">${x.badge?`<span class="dish-badge">${x.badge}</span>`:''}${x.isAvailable?'':'<span class="unavailable-badge">Unavailable</span>'}${x.image?`<img src="${x.image}" alt="${x.name}">`:'<span class="dish-photo-placeholder">Food image</span>'}</div><div class="dish-body"><h3>${x.name}</h3><p>${x.desc}</p><div class="dish-footer"><span class="price">${money(x.price)}</span><button class="add-btn ${x.isAvailable?'':'unavailable-add'}" data-add="${x.id}" aria-label="${x.isAvailable?`Add ${x.name} to cart`:`${x.name} is unavailable`}" ${x.isAvailable?'':'disabled'}>${x.isAvailable?'+':'Unavailable'}</button></div></div></article>`).join('')}
function renderPagination(total){const pages=Math.ceil(total/PAGE_SIZE);const nav=$('.menu-pagination');state.page=Math.min(Math.max(1,state.page),Math.max(1,pages));nav.classList.toggle('hidden',pages<=1);nav.innerHTML=pages<=1?'':`<button data-page="${state.page-1}" ${state.page===1?'disabled':''} aria-label="Previous page">←</button>${Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${state.page===i+1?'active':''}" aria-label="Page ${i+1}" ${state.page===i+1?'aria-current="page"':''}>${i+1}</button>`).join('')}<button data-page="${state.page+1}" ${state.page===pages?'disabled':''} aria-label="Next page">→</button>`}
function renderMenu(){const all=MenuModel.filter(state.category,state.search);renderPagination(all.length);const start=(state.page-1)*PAGE_SIZE;const dishes=all.slice(start,start+PAGE_SIZE);$('.menu-view .menu-grid').innerHTML=dishCards(dishes);$('.empty-menu').classList.toggle('hidden',all.length>0)}
function renderFeatured(){const tagged=MenuModel.items.filter(x=>x.badge);const dishes=(tagged.length>=4?tagged:MenuModel.items).slice(0,4);$('.featured-grid').innerHTML=dishCards(dishes)}
function cartTotal(){return state.cart.reduce((n,x)=>n+x.price*x.qty,0)}
function renderCart(){const count=state.cart.reduce((n,x)=>n+x.qty,0);$('.cart-count').textContent=count;$('.cart-items').innerHTML=state.cart.map(x=>`<div class="cart-item"><div class="cart-item-art">${x.image?`<img src="${x.image}" alt="">`:'<span>No image</span>'}</div><div><h4>${x.name}</h4><small>${money(x.price)}</small><div class="qty-control"><button data-qty="${x.id}" data-change="-1">−</button><b>${x.qty}</b><button data-qty="${x.id}" data-change="1">+</button></div></div><button class="remove-item" data-remove="${x.id}" aria-label="Remove ${x.name}">×</button></div>`).join('');const empty=!state.cart.length;$('.cart-empty').classList.toggle('hidden',!empty);$('.cart-summary').classList.toggle('hidden',empty);$('.cart-subtotal').textContent=money(cartTotal());$('.cart-total').textContent=money(cartTotal()+49);StoreModel.write('cart',state.cart);if(state.user)StoreModel.saveCart(state.cart).catch(error=>toast(error.message))}
function addToCart(id){const product=MenuModel.find(id);if(!product?.isAvailable)return toast('This product is currently unavailable');const item=state.cart.find(x=>x.id===id);if(item)item.qty++;else state.cart.push({...product,qty:1});renderCart();toast('Added to your cart')}
function setUser(user){state.user=user;StoreModel.write('user',user);renderAccount();renderOrders()}
function renderAccount(){const logged=!!state.user;$('.login-btn').classList.toggle('hidden',logged);$('.profile-btn').classList.add('hidden');$('.sidebar-profile').classList.remove('hidden');$('.sidebar-settings').classList.toggle('hidden',!logged);$('.sidebar-account').classList.toggle('hidden',!logged);$('.sidebar-logout').classList.toggle('hidden',!logged);$('.sidebar-profile-name').textContent=logged?state.user.name:'Guest';$('.sidebar-avatar').textContent=logged?state.user.name[0].toUpperCase():'G';renderProfile()}
function statusIndex(order){if(order.status)return Math.max(0,STATUS.indexOf(order.status));const elapsed=(Date.now()-order.createdAt)/60000;return order.manualStatus??Math.min(3,Math.floor(elapsed/2))}
function statusClass(status){return {'Order placed':'status-placed','Preparing':'status-preparing','Out for delivery':'status-delivery','Delivered':'status-delivered','Cancelled':'status-cancelled'}[status]||'status-placed'}
function orderCards(orders,allowCancel=false){return orders.map(o=>{const cancelled=o.status==='Cancelled',si=statusIndex(o),status=cancelled?'Cancelled':STATUS[si];return `<article class="order-card"><div class="order-top"><div><strong class="order-id">Order #${o.id}</strong><span class="order-date">${orderDate(o.createdAt)}</span></div><span class="status-pill ${statusClass(status)}">${status}</span></div><p class="order-items-summary">${o.items.map(x=>`${x.qty}× ${x.name}`).join(' · ')}</p>${cancelled?'':`<div class="tracker">${STATUS.map((s,i)=>`<div class="track-step ${i<=si?'done':''} ${i===si?'current':''}"><span class="track-dot"></span>${s}</div>`).join('')}</div>`}<div class="order-bottom"><strong>${money(o.total)}</strong><div class="order-actions"><button class="mini-btn" data-pdf="${o.id}">Receipt PDF</button><button class="mini-btn" data-email="${o.id}">Email details</button>${allowCancel&&o.status==='Order placed'?`<button class="mini-btn cancel-order-btn" data-cancel-order="${o.id}">Cancel order</button>`:''}</div></div></article>`}).join('')}
function noOrdersMarkup(){return `<div class="orders-gate"><div class="gate-icon">🥣</div><h3>No orders yet</h3><p>Your first delicious order is only a few clicks away.</p><a class="primary-btn" href="#menu">Browse the menu</a></div>`}
function renderOrders(){const logged=!!state.user;$('.orders-gate').classList.toggle('hidden',logged);$('.orders-list').classList.toggle('hidden',!logged);if(!logged)return;$('.orders-list').innerHTML=state.orders.length?orderCards(state.orders,true):noOrdersMarkup();renderProfile()}
function renderProfile(){const logged=!!state.user;$('.profile-gate').classList.toggle('hidden',logged);$('.profile-content').classList.toggle('hidden',!logged);if(!logged)return;$('.profile-full-name').textContent=state.user.name;$('.profile-username').textContent=`@${state.user.username||'customer'}`;$('.profile-large-avatar').textContent=state.user.name[0].toUpperCase();$('.profile-email').textContent=state.user.email;$('.profile-phone').textContent=`${state.user.phoneCountry||''} ${state.user.phone||''}`.trim()||'—';$('.profile-address').textContent=[state.user.address,state.user.zipCode,state.user.country].filter(Boolean).join(', ')||'—';$('.profile-order-count').textContent=state.orders.length;$('.profile-orders-list').innerHTML=state.orders.length?orderCards(state.orders,true):noOrdersMarkup()}
async function cancelCustomerOrder(orderNumber){if(!confirm(`Cancel order #${orderNumber}? This cannot be undone.`))return;try{const response=await StoreModel.cancelOrder(orderNumber);state.orders=response.orders;StoreModel.write('orders',state.orders);renderOrders();toast('Order cancelled successfully')}catch(error){toast(error.message)}}
function openLayer(selector){$('.backdrop').classList.remove('hidden');$(selector).classList.remove('hidden')}
function closeLayers(){$('.backdrop').classList.add('hidden');$$('.modal').forEach(x=>x.classList.add('hidden'));$('.cart-drawer').classList.remove('open');$('.cart-drawer').setAttribute('aria-hidden','true');$('.customer-sidebar').classList.remove('open');$('.customer-sidebar').setAttribute('aria-hidden','true');$('.hamburger-btn').setAttribute('aria-expanded','false')}
function openCart(){$('.backdrop').classList.remove('hidden');$('.cart-drawer').classList.add('open');$('.cart-drawer').setAttribute('aria-hidden','false')}
function openSidebar(){closeLayers();$('.backdrop').classList.remove('hidden');$('.customer-sidebar').classList.add('open');$('.customer-sidebar').setAttribute('aria-hidden','false');$('.hamburger-btn').setAttribute('aria-expanded','true')}
function checkout(){if(!state.cart.length)return;if(!state.user){closeLayers();openLayer('.login-modal');toast('Log in before checking out');return}const form=$('#checkout-form'),subtotal=cartTotal(),totalItems=state.cart.reduce((sum,item)=>sum+item.qty,0);const savedAddress=[state.user.address,state.user.zipCode,state.user.country].filter(Boolean).join(', ');const savedPhone=`${state.user.phoneCountry||''}${state.user.phone||''}`.replace(/\D/g,'');if(savedAddress&&!form.address.value)form.address.value=savedAddress;if(savedPhone&&!form.phone.value)form.phone.value=savedPhone;$('.checkout-unique-items').textContent=state.cart.length;$('.checkout-total-items').textContent=totalItems;$('.checkout-subtotal').textContent=money(subtotal);$('.checkout-total-amount').textContent=money(subtotal+49);closeLayers();openLayer('.checkout-modal')}
async function placeOrder(form){const data=Object.fromEntries(new FormData(form));const button=form.querySelector('[type="submit"]');button.disabled=true;button.innerHTML='<span>Placing order…</span>';try{await StoreModel.saveCart(state.cart);const response=await StoreModel.createOrder(data);const order=response.order;state.orders.unshift(order);StoreModel.write('orders',state.orders);state.cart=[];StoreModel.write('cart',[]);renderCart();renderOrders();form.reset();state.activeOrder=order;closeLayers();$('.success-copy').textContent=`Thanks, ${state.user.name.split(' ')[0]}. Order #${order.id} is being prepared. Download your receipt or send the confirmation to ${state.user.email}.`;openLayer('.success-modal')}catch(error){toast(error.message)}finally{button.disabled=false;button.innerHTML='<span>Place order</span><b>→</b>'}}
function pdfEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'')}
function downloadPDF(order){let lines=[['SAVORLY KITCHEN',18],['ORDER RECEIPT',14],[`Receipt #${order.id}`,10],[`${orderDate(order.createdAt,true)} (Philippine Time)`,10],['',10],[`Customer: ${order.customer}`,10],[`Email: ${order.email}`,10],[`Delivery: ${order.address}`,10],[`Payment: ${order.payment}`,10],['',10],['ORDER DETAILS',12],...order.items.map(x=>[`${x.qty} x ${x.name}     PHP ${x.price*x.qty}`,10]),['',10],[`Subtotal: PHP ${order.subtotal}`,10],[`Delivery: PHP ${order.delivery}`,10],[`TOTAL: PHP ${order.total}`,13],['',10],['Thank you for ordering with Savorly!',10]];let y=790;const stream=lines.map(([t,size])=>{const out=`BT /F1 ${size} Tf 55 ${y} Td (${pdfEscape(t)}) Tj ET`;y-=size+9;return out}).join('\n');const objs=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let pdf='%PDF-1.4\n',offs=[0];for(let i=1;i<objs.length;i++){offs[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)pdf+=`${String(offs[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer << /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'}));a.download=`Savorly-Receipt-${order.id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Receipt PDF downloaded')}
function emailOrder(order){const subject=encodeURIComponent(`Savorly Order Confirmation #${order.id}`),body=encodeURIComponent(`Hi ${order.customer},\n\nYour Savorly order #${order.id} is confirmed.\n\n${order.items.map(x=>`${x.qty} x ${x.name} - PHP ${x.price*x.qty}`).join('\n')}\n\nTotal: PHP ${order.total}\nDelivery address: ${order.address}\nPayment: ${order.payment}\n\nThank you for ordering with Savorly!`);location.href=`mailto:${encodeURIComponent(order.email)}?subject=${subject}&body=${body}`;toast('Opening your email app')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),cat=e.target.closest('[data-category]'),page=e.target.closest('[data-page]'),qty=e.target.closest('[data-qty]'),remove=e.target.closest('[data-remove]'),pdf=e.target.closest('[data-pdf]'),email=e.target.closest('[data-email]'),cancel=e.target.closest('[data-cancel-order]');if(add)addToCart(+add.dataset.add);if(cat){state.category=cat.dataset.category;state.page=1;renderCategories();renderMenu()}if(page&&!page.disabled){state.page=+page.dataset.page;renderMenu();$('.menu-section').scrollIntoView({behavior:'smooth'})}if(qty){const x=state.cart.find(i=>i.id===+qty.dataset.qty);x.qty+=+qty.dataset.change;if(x.qty<1)state.cart=state.cart.filter(i=>i.id!==x.id);renderCart()}if(remove){state.cart=state.cart.filter(i=>i.id!==+remove.dataset.remove);renderCart()}if(pdf)downloadPDF(state.orders.find(o=>o.id===pdf.dataset.pdf));if(email)emailOrder(state.orders.find(o=>o.id===email.dataset.email));if(cancel)cancelCustomerOrder(cancel.dataset.cancelOrder);if(e.target.closest('.hamburger-btn'))openSidebar();if(e.target.closest('.sidebar-close')||e.target.closest('.sidebar-nav a'))closeLayers();if(e.target.closest('.cart-trigger'))openCart();if(e.target.closest('.close-btn')||e.target.closest('.backdrop')||e.target.closest('.modal-close'))closeLayers();if(e.target.closest('.login-btn')||e.target.closest('.login-btn-inline'))openLayer('.login-modal');if(e.target.closest('.checkout-btn'))checkout();if(e.target.closest('.download-receipt'))downloadPDF(state.activeOrder);if(e.target.closest('.email-confirmation'))emailOrder(state.activeOrder);if(e.target.closest('.close-success')){closeLayers();location.hash='orders'}});
$('#menu-search').addEventListener('input',e=>{state.search=e.target.value.toLowerCase().trim();state.page=1;renderMenu()});
async function applyCustomerAuth(response,guestCart){setUser(response.user);state.orders=response.orders;state.cart=response.cart;for(const guest of guestCart){const existing=state.cart.find(x=>x.id===guest.id);if(existing)existing.qty=Math.max(existing.qty,guest.qty);else state.cart.push(guest)}await StoreModel.saveCart(state.cart);StoreModel.write('cart',state.cart);StoreModel.write('orders',state.orders);renderCart();renderOrders();closeLayers();toast(`Welcome, ${response.user.name.split(' ')[0]}!`)}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]'),guestCart=[...state.cart];button.disabled=true;button.textContent='Logging in…';try{const response=await StoreModel.login(Object.fromEntries(new FormData(form)));await applyCustomerAuth(response,guestCart);form.reset()}catch(error){toast(error.message)}finally{button.disabled=false;button.innerHTML='Login <span>→</span>'}});
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]'),details=Object.fromEntries(new FormData(form)),guestCart=[...state.cart];if(details.password!==details.passwordConfirmation){toast('Passwords do not match');return}button.disabled=true;button.textContent='Creating account…';try{const response=await StoreModel.register(details);await applyCustomerAuth(response,guestCart);form.reset()}catch(error){toast(error.message)}finally{button.disabled=false;button.innerHTML='Create account <span>→</span>'}});
$('.open-signup').addEventListener('click',()=>{closeLayers();openLayer('.signup-modal')});
$('.open-login').addEventListener('click',()=>{closeLayers();openLayer('.login-modal')});
function openProfileEditor(){if(!state.user){closeLayers();openLayer('.login-modal');return}const form=$('#profile-form'),signup=$('#signup-form');const phoneSelect=form.elements.namedItem('phoneCountry'),countrySelect=form.elements.namedItem('country');phoneSelect.innerHTML=signup.elements.namedItem('phoneCountry').innerHTML;countrySelect.innerHTML=signup.elements.namedItem('country').innerHTML;['firstName','surname','username','email','phone','address','zipCode'].forEach(name=>form.elements.namedItem(name).value=state.user[name]||'');phoneSelect.value=state.user.phoneCountry||'+63';countrySelect.value=state.user.country||'Philippines';closeLayers();openLayer('.profile-modal')}
$('#profile-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='Saving…';try{const response=await StoreModel.updateProfile(Object.fromEntries(new FormData(form)));state.user=response.user;state.orders=state.orders.map(order=>({...order,email:state.user.email,customer:state.user.name}));StoreModel.write('user',state.user);StoreModel.write('orders',state.orders);renderAccount();renderOrders();closeLayers();toast('Profile updated successfully')}catch(error){toast(error.message)}finally{button.disabled=false;button.innerHTML='Save changes <span>→</span>'}});
$('.sidebar-profile').addEventListener('click',()=>{closeLayers();location.hash=state.user?'profile':'home';if(!state.user)openLayer('.login-modal')});
$('.sidebar-settings').addEventListener('click',openProfileEditor);
$('.edit-profile-page').addEventListener('click',openProfileEditor);
$('#checkout-form').addEventListener('submit',e=>{e.preventDefault();placeOrder(e.target)});
async function logoutCustomer(){if(!confirm('Log out of Savorly?'))return;try{await StoreModel.logout()}catch{}state.user=null;state.cart=[];state.orders=[];StoreModel.remove('user');StoreModel.remove('cart');StoreModel.remove('orders');closeLayers();renderAccount();renderCart();renderOrders();toast('You have been logged out')}
$('.sidebar-logout').addEventListener('click',logoutCustomer);
function showView(){const requested=(location.hash||'#home').slice(1);const view=['home','menu','orders','profile'].includes(requested)?requested:'home';$$('.page-view').forEach(el=>el.classList.toggle('hidden',el.dataset.view!==view));$$('.nav a,.sidebar-nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${view}`));if(view==='orders')renderOrders();if(view==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
window.addEventListener('hashchange',showView);
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLayers()});
async function initialize(){renderCategories();renderMenu();renderFeatured();renderCart();renderAccount();renderOrders();showView();try{const data=await StoreModel.bootstrap();if(data.menu?.length){MenuModel.items=data.menu}state.user=data.user;state.cart=data.cart||state.cart;state.orders=data.orders||[];if(state.user)StoreModel.write('user',state.user);renderCategories();renderMenu();renderFeatured();renderCart();renderAccount();renderOrders()}catch(error){toast('Connect XAMPP MySQL to enable database features')}}
async function refreshCustomerOrders(){if(!state.user)return;try{const previous=new Map(state.orders.map(order=>[order.id,order.status]));const response=await StoreModel.loadOrders();const changed=response.orders.find(order=>previous.has(order.id)&&previous.get(order.id)!==order.status);state.orders=response.orders;StoreModel.write('orders',state.orders);renderOrders();if(changed)toast(`Order #${changed.id} is now ${changed.status}`)}catch(error){console.warn('Order sync paused:',error.message)}}
initialize();setInterval(refreshCustomerOrders,10000);window.addEventListener('focus',refreshCustomerOrders);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshCustomerOrders()});
