<?php
declare(strict_types=1);

require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../models/Customer.php';

$token=trim($_REQUEST['token']??'');$success=false;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{$password=$_POST['password']??'';$confirmation=$_POST['passwordConfirmation']??'';if($password!==$confirmation)throw new RuntimeException('The passwords do not match.');(new Customer(Database::connection()))->resetPassword($token,$password);$success=true;}catch(Throwable $exception){$error=$exception->getMessage();}
}
$proto=($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https'||(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_X_FORWARDED_HOST']??$_SERVER['HTTP_HOST']??'localhost';$path=str_replace('\\','/',dirname(dirname(dirname($_SERVER['SCRIPT_NAME']??'/'))));$base=$proto.'://'.$host.($path==='/'?'':$path);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset password — Savorly</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:20px;display:grid;place-items:center;background:#fbf8f1;color:#294c3d;font-family:Arial,sans-serif}.card{width:min(480px,100%);padding:38px;border-radius:24px;background:#fff;box-shadow:0 20px 60px rgba(35,62,50,.13)}.mark{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#e9f0e7;font:bold 21px Georgia,serif}h1{margin:18px 0 8px;font:600 32px Georgia,serif}p{color:#65756f;line-height:1.6}.error{padding:10px;border-radius:8px;background:#fde8e5;color:#a44337;font-size:13px}label{display:grid;gap:7px;margin:15px 0;font-size:12px;font-weight:bold}input{width:100%;padding:13px;border:1px solid #e7e5dc;border-radius:10px;outline:0}input:focus{border-color:#476f5c;box-shadow:0 0 0 3px #e9f0e7}button,a{width:100%;padding:14px;border:0;border-radius:999px;display:block;background:#476f5c;color:#fff;text-align:center;text-decoration:none;font-weight:bold;cursor:pointer}</style></head><body><main class="card"><div class="mark">S</div><?php if($success): ?><h1>Password updated</h1><p>Your password has been changed successfully. You can now return to Savorly and log in.</p><a href="<?= htmlspecialchars($base,ENT_QUOTES,'UTF-8') ?>/">Return to customer login</a><?php else: ?><h1>Choose a new password</h1><p>Enter and confirm your new customer account password.</p><?php if($error): ?><div class="error"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></div><?php endif; ?><form method="post"><input type="hidden" name="token" value="<?= htmlspecialchars($token,ENT_QUOTES,'UTF-8') ?>"><label>New password<input name="password" type="password" required minlength="6" autocomplete="new-password"></label><label>Confirm new password<input name="passwordConfirmation" type="password" required minlength="6" autocomplete="new-password"></label><button type="submit">Update password</button></form><?php endif; ?></main></body></html>
